export const platforms = [
  "Google Reviews",
  "Zomato",
  "App Store",
  "Play Store",
];

export const feelBasedOnRating: Record<string, any> = {
  ["1"]: [
    "Terrible",
    "Awful",
    "Disastrous",
    "Dreadful",
    "Unacceptable",
    "Pathetic",
    "Lousy",
    "Miserable",
    "Subpar",
  ],
  ["2"]: [
    "Mediocre",
    "Substandard",
    "Average",
    "Unsatisfactory",
    "Lackluster",
    "Disappointing",
    "Underwhelming",
    "Marginal",
    "Fair",
    "Ordinary",
    "Passable",
    "So-so",
    "Meh",
    "Okay",
    "Adequate",
  ],
  ["3"]: [
    "Decent",
    "Average",
    "Fair",
    "Acceptable",
    "Satisfactory",
    "Adequate",
    "Okay",
    "Alright",
    "Middle-of-the-road",
    "Passable",
    "Reasonable",
    "Okayish",
    "Tolerable",
    "Moderate",
    "Not bad",
  ],
  ["4"]: [
    "Very good",
    "Great",
    "Impressive",
    "Solid",
    "High-quality",
    "Commendable",
    "Admirable",
    "Well-done",
    "Fine",
    "Good",
    "Noteworthy",
    "Above average",
    "Promising",
    "Praiseworthy",
  ],
  ["5"]: [
    "Excellent",
    "Great",
    "Fantastic",
    "Wonderful",
    "Terrific",
    "Superb",
    "Outstanding",
    "Impressive",
    "Remarkable",
    "Exceptional",
    "Amazing",
    "Very good",
    "High-quality",
    "Top-notch",
    "Solid",
  ],
};
